- hosts: web
  become: yes


  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /home/centos/ansible/test.yml
        dest: /home/centos/test.yml
        