--- #this is my demo play book
- hosts: web
  user: ansible
  become: yes

  tasks:
  - name: Install the latest version of Apache
  ansible.builtin.yum:
    name: nginx
    state: latest
  - name: Start service httpd, if not started
    service:
    name: nginx
    state: started
