- hosts: all
  become: yes
  vars:
  pkg: nginx
  tasks:
  - name: Install the latest version of Apache
    ansible.builtin.yum:
     name: "{{pkg}}"
     state: latest
  - name: Start service httpd, if not started
    service:
     name: "{{pkg}}"
     state: started
